spring:
  profiles:
    active:
    - dev
---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: shopconfig-config-client
eureka:
  client:  
    service-url:
      defaultZone: http://edmin:shopjava@eureka-dev.com:7001/eureka
---
server:
  port: 8202
spring:
  profiles: beta
  application:
    name: shopconfig-config-client
eureka:
  client:  
    service-url:
      defaultZone: http://edmin:shopjava@eureka-beta.com:7001/eureka